image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001
    onOpen: ignore
tasks:
  - init: 'cd gitpod-example && npm install && nuxt build'
    command: 'cd gitpod-example && nuxt start'
  - command: 'json-server db.json --port 3001'
